name: ci

on: push

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        toolchain: [stable, nightly]

    steps:
      - uses: actions/checkout@v4

      - name: Install Rust toolchain
        run: |
          rustup set profile minimal
          rustup update --no-self-update $RUST_CHANNEL
          rustup component add --toolchain $RUST_CHANNEL rustfmt clippy
        env:
          RUST_CHANNEL: ${{ matrix.toolchain }}

      - run: cargo build
      - run: cargo test
      - run: cargo clippy --workspace --all-targets --all-features --no-deps -- -D warnings
